config/routes.rb
Movielist::Application.routes.draw do

  
  match 'feed' => 'movies#feed', :format => 'rss', :as => :feed
  match 'togglegroupedview' => 'users#togglegroupedview', :as => :togglegroupedview
  match 'logout' => 'users#logout', :as => :logout
  match 'ajax/collections' => 'ajax#collections'
  match 'movies/search' => 'movies#search', :as => :search
  
  post "/movies/auto_complete_for_movie_collection_name" => "movies#auto_complete_for_movie_collection_name"
  
  resources :movies
  resources :collections, :only => [:index, :show, :edit, :update]
  
  root :to => 'users#login'
end

app/models/collection.rb
class Collection < ActiveRecord::Base

  has_many :movies
  
  validates_presence_of :collection_title
  
  def to_param 
    "#{id}-#{collection_title.downcase.gsub(/[^a-z1-9]+/i, '-')}" 
  end  
  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  before_filter :authorize

  helper :movies_render

  def index
    @collections = Collection.all(:conditions => ['collection_title LIKE ?', "%#{params[:search]}%"])
  end
  
  def show
    collection_id = params[:id].to_i
    @movies = Movie.find_all_by_collection_id(collection_id)
    @collection = Collection.find_by_id(collection_id)
  end
  
  def edit
    @collection = Collection.find(params[:id])
  end 
  
  def update
    begin
      @collection = Collection.find(params[:id])
      @collection.attributes = params[:collection]
      @collection.save!
      flash[:notice] = 'Collection successfully edited!'
      redirect_to collection_path 
    rescue
      flash[:error] = 'An error occured during the editing of the collection!'
      render :action => 'edit'     
    end   
  end

end

app/views/collections/_form.html.erb
<%= form_for @collection, :html => { :multipart => true } do |f| %>    

<%# error_messages_for :collection %>  
 
  <fieldset>    
    <legend><%= title %></legend>
    <p>
      <%= f.label :collection_title %>
      <%= f.text_field :collection_title %>
    </p>
    <p>
      <%= f.label :collection_original_title %>
      <%= f.text_field :collection_original_title %>
    </p>
    <p>
      <%= f.submit 'Submit' %>
    </p>
    <p>
      <%= link_to 'Cancel', :back || movies_path %>
    </p>
  </fieldset>
<% end %>

app/views/collections/edit.html.erb
<% title 'edit collection'%>

<%# error_messages_for :collections %>     

<%= render :partial => "form", :locals => { :title => 'Edit Collection' } %>

app/views/collections/index.js.erb
<%= auto_complete_result @collections, :collection_title %>

app/views/collections/show.html.erb
<%- title @collection.collection_title || "" -%>
<h2>
  <% if @movies.first.disc_type == 'bluray' %>
	  <%=image_tag('/images/icon_blurays.png') %>
	<% else %>
	  <%=image_tag('/images/icon_dvds.png') %>
	<% end%>
	<%= link_to @collection.collection_title, edit_collection_url %>
</h2>

<%- unless @movies.nil? -%>

	<% for movie in @movies %>

		<%= show_movie movie %>
	
	<% end %>

<%- end -%>