config/routes.rb
Movielist::Application.routes.draw do

  
  match 'feed' => 'movies#feed', :format => 'rss', :as => :feed
  match 'togglegroupedview' => 'users#togglegroupedview', :as => :togglegroupedview
  match 'logout' => 'users#logout', :as => :logout
  match 'ajax/collections' => 'ajax#collections'
  match 'movies/search' => 'movies#search', :as => :search
  
  post "/movies/auto_complete_for_movie_collection_name" => "movies#auto_complete_for_movie_collection_name"
  
  resources :movies
  resources :collections, :only => [:index, :show, :edit, :update]
  
  root :to => 'users#login'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  auto_complete_for :movie, :collection_name
  
  before_filter :authorize, :except => [:feed]
  before_filter :http_authenticate, :only => [:feed]
  
  helper :movies_render  
  
  def index
    @user = User.find_by_id session[:user_id]
    @movies = Movie.all
    
    collection_ids = []
    movies_to_be_removed = []
    for movie in @movies
      unless movie.collection_id.nil?
        collection_ids << movie.collection_id
      end
    end
    collection_ids.uniq!

    for movie in @movies
      unless movie.collection_id.nil?
        if collection_ids.include? movie.collection_id 
          collection_ids.delete movie.collection_id
        else
          movies_to_be_removed << movie
        end
      end
    end

    for movie in movies_to_be_removed
      @movies.delete(movie)
    end
    
    @movies_users = @movies.group_by { |m| m.user.realname }
  end
  
  def search
    @movies = Movie.search(params[:search])
  end
  
  def feed
    @movies = Movie.all(:order => 'ID DESC', :limit => 20)
  end
  
  def show
    begin
      @movie = Movie.find(params[:id].to_i)
    rescue ActiveRecord::RecordNotFound
      flash[:error] = 'Movie not found!'
      redirect_to root_url
    end
  end
  
  def new
    @movie = Movie.new
    @collections = Collection.all(:order => 'id ASC')
    @collections.insert(0, Collection.new(:collection_title => ''))
  end
  
  def create
    begin
      @movie = Movie.new(params[:movie])
      user = User.find_by_id session[:user_id]
      @movie.user_id = user.id
      
      set_collection
      set_purchase_date
      set_foreign_language
      
      @movie.save!
      flash[:notice] = 'Movie successfully created!'
      redirect_to movies_path
    rescue
      flash[:error] = 'An error occured during the creation of the movie!'
      render :action => 'new'
    end
  end  
  
  def edit
    @movie = Movie.find(params[:id])
  end 
  
  def update
    begin
      @movie = Movie.find(params[:id])
      @movie.attributes = params[:movie]

      set_collection
      set_purchase_date
      set_foreign_language
      
      @movie.save!
      flash[:notice] = 'Movie successfully edited!'
      redirect_to movie_path   
    rescue
      flash[:error] = 'An error occured during the editing of the movie!'
      render :action => 'edit'
    end  
  end
  
  def destroy
    @movie_to_destroy = Movie.find(params[:id])
    @movie_to_destroy.destroy
    flash[:notice] = 'Movie successfully deleted!'
    redirect_to movies_path
  end
  
  protected

    def http_authenticate
      authenticate_or_request_with_http_basic do |username, password|
        @user = User.authenticate(username, password)
      end
    end
    
    def set_collection
      # collection is changed or deleted
      if params[:movie][:collection_name] == '' || (params[:movie][:collection_name] != '' && @movie.collection_id.nil?) || params[:movie][:collection_name] != @movie.collection.collection_title
        @count_of_collection_referenced = Movie.find_all_by_collection_id(@movie.collection_id)
        # delete references to the collection, because no movie is referencing it anymore
        unless @count_of_collection_referenced.length > 1
          Collection.find(@movie.collection_id).destroy if @movie.collection_id
        end
        if params[:movie][:collection_name] == ''
          @movie.collection_id = nil # delete the reference to the collection
        elsif params[:movie][:collection_name] != ''
          collection = Collection.find_by_collection_title(params[:movie][:collection_name])
          if collection.blank?
            collection = Collection.new(:collection_title => params[:movie][:collection_name])
            collection.save!
          end
          @movie.collection = collection
        end
      end
    end
    
    def set_purchase_date
      if params[:movie][:bought_at].present?
        date_array = params[:movie][:bought_at].split("/") 
        @movie.bought_at = "#{date_array[2]}-#{date_array[1]}-#{date_array[0]} 00:00:00"
      else
        @movie.bought_at = "#{Time.now.localtime.strftime("%Y-%m-%d")} 00:00:00"
      end      
    end
    
    def set_foreign_language
      if params[:movie][:foreign_language] == ""
        @movie.foreign_language = nil
      end      
    end
end

app/helpers/movies_helper.rb
module MoviesHelper 
	
	def index_table user, movies, grouped_view
	  return_string = '<h4>' + user + ' (' + movies.length.to_s + ')</h4>'
		return_string << '<table width="100%" class="sortable" id="sortabletable_' + user  + '">'
		
		return_string << index_table_header(grouped_view)

		for movie in movies
		  return_string << index_table_content_row(movie, grouped_view)
		end

		return_string << '</table>'
	  return_string << '<br />'
	  return_string.html_safe
	end
	
	private
	
  	def index_table_header grouped_view
  	  return_string = '<tr>'
  		return_string	<< ' <th class="unsortable">&nbsp;</th>'
      return_string << ' <th>title</th>'
  		return_string	<< ' <th>original title</th>'
  		return_string	<< ' <th>purchase date</th>'
  		return_string	<< ' <th>media type</th>'
  		return_string	<< ' <th>parental rating</th>'
  		unless grouped_view
  		  return_string << ' <th>owner</th>'
  		end
      return_string << '</tr>'
      return_string
  	end
	
  	def index_table_content_row movie, grouped_view
  	  return_string = '<tr>'
  		return_string << '	<td>'
		
  		if movie.collection_id.nil?
  		  if movie.disc_type == 'bluray'
  		    return_string << link_to(image_tag('/images/icon_bluray.png'), movie.imdb_link)
  		  else
  		    return_string << link_to(image_tag('/images/icon_dvd.png'), movie.imdb_link)
  		  end
  		else
  		  if movie.disc_type == 'bluray'
  		    return_string << link_to(image_tag('/images/icon_blurays.png'), movie.imdb_link)
  		  else
  		    return_string << link_to(image_tag('/images/icon_dvds.png'), movie.imdb_link)
  		  end
  		end
		
  		return_string << '	</td>'
      return_string << '  <td>'
      
      unless movie.foreign_language.nil?
      	return_string << image_tag('/images/flags/'+movie.foreign_language+'.png', :alt => 'language: ' + movie.foreign_language) + '&nbsp;'.html_safe
      end
    
  		if movie.collection_id.nil?
  		  return_string << link_to(movie.movie_title, movie_url(movie))
  		else
  		  return_string << link_to(movie.collection.collection_title, collection_url(movie.collection))
  		end
		
  		return_string << '	</td>'
  		return_string << '	<td>'
		
  		if movie.collection_id.nil?
  		  return_string << '<i>' + link_to(movie.movie_original_title, movie_url(movie)) + '</i>'
  		else
  		  unless movie.collection.collection_original_title.nil?
  		    return_string << movie.collection.collection_original_title
  		  end
  		end
		
  		return_string << '	</td>'
  		return_string << '	<td>' + movie.formatted_bought_at + '</td>'
  		return_string << '	<td>' + movie.media_type + '</td>'
  		return_string << '	<td>' + movie.parental_rating + '</td>'
  		unless grouped_view
  		  return_string << '	<td>' + movie.user.realname + '</td>'
  		end
      return_string << '</tr>'
  	  return_string.html_safe
  	end
	
end

app/views/movies/_form.html.erb
<%# error_messages_for :movie %>   

<%= form_for @movie, :html => { :multipart => true } do |f| %>    

<fieldset>    
	<legend><%= title %></legend>
	<p>
		<%= f.label :movie_title %>
		<%= f.text_field :movie_title %>
	</p>
	<p>
		<%= f.label :movie_original_title %>
		<%= f.text_field :movie_original_title %>
	</p>
	<p>
		<%= f.label :bought_at, 'Purchase date' %>
		<%= f.text_field :bought_at, :value => @movie.formatted_bought_at %>
	</p>
	<p>
		<%= f.label :imdb_link %>
		<%= f.text_field :imdb_link %>
		</p>
	<p>
		<%= f.label :media_type %>
		<%= f.select(:media_type, [[@movie.media_type, @movie.media_type], ["movie", :movie], ["series", :series]])%>
		</p>
	<p>
		<%= f.label :disc_type %>
		<%= f.select(:disc_type, [[@movie.disc_type, @movie.disc_type], ["dvd", :dvd], ["bluray", :bluray]])%>
	</p>
	<p>
		<%= f.label :parental_rating %>
		<%= f.select(:parental_rating, [[@movie.parental_rating, @movie.parental_rating], ["usk 18", 18], ["usk 16", 16], ["usk 12", 12], ["usk 6", 6], ["usk ohne", 0]])%>
	</p>
	<p>
		<%= f.label :foreign_language %>
		<%= f.select(:foreign_language, [[@movie.foreign_language, @movie.foreign_language], ["", ""], ["english", :gb], ["spanish", :es], ["german", :de], ["french", :fr]])%>
	</p>
	<p>
		<%= f.label :photo %>
		<%= f.file_field :photo %>
	</p>
	<p>
	  <%= f.label :collection_name %>
    <%= f.text_field :collection_name %>
    <%= f.hidden_field :collection_id %>
	</p>
	<p>
		<%= f.submit 'Submit' %>
	</p>
	<p>
	 		<%= link_to 'Cancel', :back || movies_path %>
	</p>
</fieldset>
<% end %>

app/views/movies/edit.html.erb
<% title 'edit movie'%>

<%= render :partial => "form", :locals => { :title => 'Edit Movie' } %>

app/views/movies/index.html.erb
<% title "index" %>

<h3>
	Movie List
</h3>

<p style="float: right;">
	<%= link_to 'toggle grouped user view', togglegroupedview_url %>
</p>

<%- if @user.show_grouped_by_user == true -%>

	<%- @movies_users.sort.each do |user, movies| -%>
	
		<%= index_table user, movies, @user.show_grouped_by_user %>
	
	<%- end -%>
	
<%- else -%>

	<%= index_table "All movies", @movies, @user.show_grouped_by_user %>

<%- end -%>

app/views/movies/new.html.erb
<% title 'new movie'%>

<%= render :partial => "form", :locals => { :title => 'New Movie' } %>

app/views/movies/search.html.erb
<%- unless @movies.nil? -%>

	<% for movie in @movies %>

		<%= show_movie movie %>
	
	<% end %>

<%- end -%>

app/views/movies/show.html.erb
<%- title @movie.movie_title || "" -%>

<%= show_movie @movie, @movie.collection %>