config/routes.rb
Movielist::Application.routes.draw do

  
  match 'feed' => 'movies#feed', :format => 'rss', :as => :feed
  match 'togglegroupedview' => 'users#togglegroupedview', :as => :togglegroupedview
  match 'logout' => 'users#logout', :as => :logout
  match 'ajax/collections' => 'ajax#collections'
  match 'movies/search' => 'movies#search', :as => :search
  
  post "/movies/auto_complete_for_movie_collection_name" => "movies#auto_complete_for_movie_collection_name"
  
  resources :movies
  resources :collections, :only => [:index, :show, :edit, :update]
  
  root :to => 'users#login'
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>movie list - <%= yield(:title) || 'movie list' %></title>
  <%= stylesheet 'application' %>
	<%= javascript 'application' %>
	<%- if logged? -%>
		<%= auto_discovery_link_tag :rss, feed_url %>
	<%- end -%>
	<%= yield(:head) %>
	<%= csrf_meta_tags %>
	<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
</head>

<body>
	<div id="main">

		<div id="header">
			<h1><%= link_to image_tag('/images/movie.png') + ' movie list', root_url %></h1>
		</div>

		<%- if logged? -%>
			<div id="search_form">
				<form action="<%= search_path %>" method="get" >
				  <p>
				    <%= text_field_tag :search, params[:search] %>
				    <%= submit_tag "Search", :name => nil %>
				  </p>
				</form>
			</div>
		<%- end -%>
		<div style="clear: both;"></div>
		<%- if logged? -%>
		<div id="menu">
			<ul>
					<li><%= link_to 'new movie', new_movie_url %></li>
					<li><%= link_to 'logout [' + User.find_by_id(session[:user_id]).username + ']', logout_path %></li>
			</ul>
		</div>
		<%- end -%>


		<div id="content">
			<%- if flash[:error] || flash[:notice] -%>
		  <div id="messages">
				<%- if flash[:error] -%>
					<div id="error"><%= flash[:error] %></div>
					<div style="clear:both;"></div>
				<%- end -%> 
				<%- if flash[:notice] -%>
					<div id="notice"><%= flash[:notice] %></div>
					<div style="clear:both;"></div>
				<%- end -%>   
			</div>	
			<%- end -%>

			<div class="yield_content">
				<%= yield %>
				<div style="clear: both;"></div>
			</div>
		</div>

		<p id="footer">
			movie list - &copy;<%= Time.now.year %> Wolfgang K&ouml;nig 
		</p>

	</div>
</body>
</html>